hari = ["Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu"]

hari_raya =["Idul Fitri", "Idul Adha"]

print(hari)
print(len(hari))
print(hari[0:4])
print(hari[-2])
print(hari.index("Sabtu"))
hari.append("Valentine")
hari.remove("Senin")
print(hari)
hari.extend(hari_raya)
print(hari)
hari.append("Senin")
print(hari)
hari.remove("Senin")
print(hari)
hari.insert(0,"Senin")
print(hari)
hari.insert(hari.index("Kamis")+1,"ASYIK")
hari.insert(hari.index("Kamis")+1,"ASYIK")
print(hari)
print(len(hari))
print(hari.count("ASYIK"))
hari.sort()
print(hari)
hari2=hari.copy()
hari.reverse()
print(hari)
print(hari2)
